[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss", "emmet-lsp"]
auto-format = true

[language-server.tailwindcss]
command = "tailwindcss-language-server"
language-id = "rust"
args = ["--stdio"]

[language-server.tailwindcss.config]
tailwindCSS = { includeLanguages = { rust = "html", "*.rs" = "html" } }

[language-server.rust-analyzer.config]
rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"] }
cargo = { allFeatures = true }

[language-server.emmet-lsp.config]
emmet = { includeLanguages = { rust = "html", "*.rs" = "html" } }
