name: linting and testing
on:
  push:
    branches:
      - "!main"
jobs:
  api:
    name: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-api
      - name: test
        run: cargo test --package vps-api
  rpc:
    name: rpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-rpc
      - name: test
        run: cargo test --package vps-rpc
