name: lint and test
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-api
      - name: test
        run: cargo test --package vps-api
  rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-rpc
      - name: test
        run: cargo test --package vps-rpc
