name: build and deploy
on: push
jobs:
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-api
      - name: test
        run: cargo test --package vps-api
  api-deploy:
    runs-on: ubuntu-latest
    needs: api-lint
    if: github.ref == 'refs/heads/main'
    uses: appleboy/ssh-action@v1
    with:
      username: ubuntu
      host: ${{ secrets.HOST }}
      key: ${{ secrets.SSH_KEY }}
      script: |
        cd service_repos/vps
        git pull --rebase
        /home/ubuntu/.cargo/bin/cargo build --release --package vps-api
        /home/ubuntu/.cargo/bin/cargo install --path vps-api
        sudo systemctl restart vps-api.service
  rpc-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: lint
        run: cargo check --package vps-rpc
      - name: test
        run: cargo test --package vps-rpc
  rpc-deploy:
    runs-on: ubuntu-latest
    needs: rpc-lint
    if: github.ref == 'refs/heads/main'
    uses: appleboy/ssh-action@v1
    with:
      username: ubuntu
      host: ${{ secrets.HOST }}
      key: ${{ secrets.SSH_KEY }}
      script: |
        cd service_repos/vps
        git pull --rebase
        /home/ubuntu/.cargo/bin/cargo build --release --package vps-rpc
        /home/ubuntu/.cargo/bin/cargo install --path vps-rpc
        sudo systemctl restart vps-rpc.service
