name: pipeline
on:
  push:
    branches:
      - gh-action
jobs:
  build:
    name: remote ssh
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: appleboy/ssh-action@v1
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            pwd
            which cargo
            cargo install --path vps-api
            sudo systemctl restart vps-api
