name: deploy
on:
  push:
    branches:
      - gh-action
jobs:
  build:
    - name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - name: lint
          run: cargo check --package vps-api
    - name: remote ssh
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: toolchain install
          uses: dtolnay/rust-toolchain@stable
        - name: lint
          run: cargo check --package vps-api
        - name: deploy api
          uses: appleboy/ssh-action@v1
          with:
            username: ubuntu
            host: ${{ secrets.HOST }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd service_repos/vps
              /home/ubuntu/.cargo/bin/cargo install --path vps-api
              sudo systemctl restart vps-api.service
        - name: deploy rpc
          uses: appleboy/ssh-action@v1
          with:
            username: ubuntu
            host: ${{ secrets.HOST }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd service_repos/vps
              /home/ubuntu/.cargo/bin/cargo install --path vps-rpc
              sudo systemctl restart vps-rpc.service
